# Generated by Django 3.2.12 on 2024-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('em', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField()),
            ],
            options={
                'db_table': 'wanafunzi',
            },
        ),
    ]
