# Generated by Django 3.2.12 on 2024-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Email_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='em',
            new_name='Email_address',
        ),
    ]
